project:
  type: website
  output-dir: docs

website:
  title: "Max Grezlik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true

editor: visual

